name: Trigger Workflow C
on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Print a message
        run: echo "Workflow C completed"
